######################################################################
# Automatically generated by qmake (2.01a) Fri Dec 16 14:36:54 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += crypto.h ui.h window.h result_widget.h result_dialog.h
SOURCES += crypto.cpp main.cpp ui.cpp window.cpp result_widget.cpp result_dialog.cpp
RESOURCES += resources.qrc

ICON = key.icns

