#############################################################################
# Makefile for building: iCrypto.app/Contents/MacOS/iCrypto
# Generated by qmake (2.01a) (Qt 4.7.4) on: Sun Jan 8 16:35:44 2012
# Project:  iCrypto.pro
# Template: app
# Command: /Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/qmake -o Makefile iCrypto.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -gdwarf-2 -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5 -Wall -W $(DEFINES)
INCPATH       = -I../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/default -I. -I../../Bin/QtSDK/Desktop/Qt/474/gcc/lib/QtCore.framework/Versions/4/Headers -I../../Bin/QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../Bin/QtSDK/Desktop/Qt/474/gcc/lib/QtGui.framework/Versions/4/Headers -I../../Bin/QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../Bin/QtSDK/Desktop/Qt/474/gcc/include -I. -I. -F/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/lib
LINK          = g++
LFLAGS        = -headerpad_max_install_names -arch x86_64 -Xarch_x86_64 -mmacosx-version-min=10.5
LIBS          = $(SUBLIBS) -F/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/lib -L/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/lib -framework QtGui -framework QtCore 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = crypto.cpp \
		main.cpp \
		ui.cpp \
		window.cpp \
		result_widget.cpp \
		result_dialog.cpp moc_ui.cpp \
		moc_window.cpp \
		moc_result_widget.cpp \
		moc_result_dialog.cpp \
		qrc_resources.cpp
OBJECTS       = crypto.o \
		main.o \
		ui.o \
		window.o \
		result_widget.o \
		result_dialog.o \
		moc_ui.o \
		moc_window.o \
		moc_result_widget.o \
		moc_result_dialog.o \
		qrc_resources.o
DIST          = ../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		iCrypto.pro
QMAKE_TARGET  = iCrypto
DESTDIR       = 
TARGET        = iCrypto.app/Contents/MacOS/iCrypto

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-gdwarf-2 \
		-arch \
		x86_64 \
		-Xarch_x86_64 \
		-mmacosx-version-min=10.5 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile iCrypto.app/Contents/PkgInfo iCrypto.app/Contents/Resources/empty.lproj iCrypto.app/Contents/Info.plist iCrypto.app/Contents/Resources/key.icns $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) iCrypto.app/Contents/MacOS/ || $(MKDIR) iCrypto.app/Contents/MacOS/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: iCrypto.pro  ../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/default/qmake.conf ../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile iCrypto.pro
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac.conf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/mac-g++.conf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_pre.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/dwarf2.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/debug.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/default_post.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/x86_64.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/objective_c.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/rez.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/mac/sdk.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile iCrypto.pro

iCrypto.app/Contents/PkgInfo: 
	@$(CHK_DIR_EXISTS) iCrypto.app/Contents || $(MKDIR) iCrypto.app/Contents 
	@$(DEL_FILE) iCrypto.app/Contents/PkgInfo
	@echo "APPL????" >iCrypto.app/Contents/PkgInfo
iCrypto.app/Contents/Resources/empty.lproj: 
	@$(CHK_DIR_EXISTS) iCrypto.app/Contents/Resources || $(MKDIR) iCrypto.app/Contents/Resources 
	@touch iCrypto.app/Contents/Resources/empty.lproj
	
iCrypto.app/Contents/Info.plist: 
	@$(CHK_DIR_EXISTS) iCrypto.app/Contents || $(MKDIR) iCrypto.app/Contents 
	@$(DEL_FILE) iCrypto.app/Contents/Info.plist
	@sed -e "s,@ICON@,key.icns,g" -e "s,@EXECUTABLE@,iCrypto,g" -e "s,@TYPEINFO@,????,g" ../../Bin/QtSDK/Desktop/Qt/474/gcc/mkspecs/default/Info.plist.app >iCrypto.app/Contents/Info.plist
iCrypto.app/Contents/Resources/key.icns: key.icns
	@$(CHK_DIR_EXISTS) iCrypto.app/Contents/Resources/ || $(MKDIR) iCrypto.app/Contents/Resources/ 
	@$(DEL_FILE) iCrypto.app/Contents/Resources/key.icns
	@$(COPY_FILE) key.icns iCrypto.app/Contents/Resources/key.icns
dist: 
	@$(CHK_DIR_EXISTS) .tmp/iCrypto1.0.0 || $(MKDIR) .tmp/iCrypto1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/iCrypto1.0.0/ && $(COPY_FILE) --parents crypto.h ui.h window.h result_widget.h result_dialog.h .tmp/iCrypto1.0.0/ && $(COPY_FILE) --parents resources.qrc .tmp/iCrypto1.0.0/ && $(COPY_FILE) --parents crypto.cpp main.cpp ui.cpp window.cpp result_widget.cpp result_dialog.cpp .tmp/iCrypto1.0.0/ && (cd `dirname .tmp/iCrypto1.0.0` && $(TAR) iCrypto1.0.0.tar iCrypto1.0.0 && $(COMPRESS) iCrypto1.0.0.tar) && $(MOVE) `dirname .tmp/iCrypto1.0.0`/iCrypto1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/iCrypto1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) -r iCrypto.app
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_moc_header_make_all: moc_ui.cpp moc_window.cpp moc_result_widget.cpp moc_result_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_ui.cpp moc_window.cpp moc_result_widget.cpp moc_result_dialog.cpp
moc_ui.cpp: crypto.h \
		result_dialog.h \
		result_widget.h \
		ui.h
	/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ ui.h -o moc_ui.cpp

moc_window.cpp: ui.h \
		crypto.h \
		result_dialog.h \
		result_widget.h \
		window.h
	/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ window.h -o moc_window.cpp

moc_result_widget.cpp: result_widget.h
	/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ result_widget.h -o moc_result_widget.cpp

moc_result_dialog.cpp: result_widget.h \
		result_dialog.h
	/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) -D__APPLE__ -D__GNUC__ result_dialog.h -o moc_result_dialog.cpp

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		img/play.png \
		img/icon.png \
		img/save.png \
		img/record.png \
		img/preview.png \
		img/open.png
	/Users/feifeihang/Bin/QtSDK/Desktop/Qt/474/gcc/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

crypto.o: crypto.cpp crypto.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o crypto.o crypto.cpp

main.o: main.cpp window.h \
		ui.h \
		crypto.h \
		result_dialog.h \
		result_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

ui.o: ui.cpp ui.h \
		crypto.h \
		result_dialog.h \
		result_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ui.o ui.cpp

window.o: window.cpp window.h \
		ui.h \
		crypto.h \
		result_dialog.h \
		result_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

result_widget.o: result_widget.cpp result_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result_widget.o result_widget.cpp

result_dialog.o: result_dialog.cpp result_dialog.h \
		result_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result_dialog.o result_dialog.cpp

moc_ui.o: moc_ui.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ui.o moc_ui.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

moc_result_widget.o: moc_result_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_result_widget.o moc_result_widget.cpp

moc_result_dialog.o: moc_result_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_result_dialog.o moc_result_dialog.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

